version: "3.9"

services: 
  app:
    container_name: "zhavia_api_task"
    build: .
    ports:
      - "3011:3011"
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://${DB_USER_POSTGRESS}:${DB_PASS_POSTGRESS}@postgres-user:5433/${DB_DATABASE_POSTGRESS}"
    depends_on:
      - postgres-task
    networks:
      - app-network

  postgres-task:
    image: postgres:alpine3.20
    container_name: "zhavia_postgres_task"
    ports: 
      - 5433:5432
    environment:
      POSTGRES_USER: ${DB_USER_POSTGRESS}
      POSTGRES_PASSWORD: ${DB_PASS_POSTGRESS}
      POSTGRES_DB: ${DB_DATABASE_POSTGRESS}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge